version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    command: [ "sh", "-c", "python manage.py migrate && exec gunicorn navigation.wsgi:application --bind 0.0.0.0:8000" ]
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "test_db", "-U", "postgres" ]
      interval: 3s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  frontend:
    image: frontend:0.0.1
    build: ../frontend
    restart: always
    ports:
      - "3000:3000"
